# docker-compose -f postgres-compose.yml up -d

version: '3.1'

services:
  postgres:
    container_name: postgres-14.1
    image: postgres:14.1
    #restart: always
    ports:
      - "5432:5432"
    #volumes:
      #- /diretorio/local/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      #POSTGRES_DB: fruit
